apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "secret-provider-kv"
  namespace: api
spec:
  provider: azure
  secretObjects:                   # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: secrets-store-creds-2             # name of the Kubernetes Secret object
    type: Opaque
    data:
    - objectName: "DatabaseLogin"   # name of the mounted content to sync, such as the object name or object alias
      key: "SQLUSER"                 # data field to populate. This must match in deployment yaml for key
    - objectName: "DatabasePassword"   # name of the mounted content to sync, such as the object name or object alias
      key: "SQLPASSWORD"                 # data field to populate. This must match in deployment yaml for key
    - objectName: "Databaseserver"  # name of the mounted content to sync, such as the object name or object alias
      key: "SQLSERVER"                   # data field to populate. This must match in deployment yaml for key
    - objectName: "Databasename"  # name of the mounted content to sync, such as the object name or object alias
      key: "SQLDBNAME"                 # data field to populate. This must match in deployment yaml for key
  parameters:
    keyvaultName: "ka-ohkeyvault0708"
    objects:  |
      array:
        - |
          objectName: "DatabaseLogin"
          objectType: secret
        - |
          objectName: "DatabasePassword"
          objectType: secret
        - |
          objectName: "Databaseserver"
          objectType: secret
        - |
          objectName: "Databasename"
          objectType: secret
    resourceGroup: teamResources
    subscriptionId: 4b94c4c4-c372-44f8-9be5-xxb44c16df
    tenantId: c4198046-524d-4751-833c-e321973xx
