apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryirf8267.azurecr.io/poi:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol
          mountPath: '/secrets'
          readOnly: true
      volumes:
      - name: vol
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure
          nodePublishSecretRef:
            name: secrets-store-creds
---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: poi
---
#A service profile is a custom Kubernetes resource (CRD) that can provide Linkerd additional information about a service. 
#In particular, it allows you to define a list of routes for the service. Each route uses a regular expression to define 
#which paths should match that route.

apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: poi.api.svc.cluster.local
  namespace: api
spec:
  routes:
  - name: GET /api
    condition:
      method: GET
      pathRegex: /api
    isRetryable: true
  retryBudget:
    retryRatio: 0.2
    minRetriesPerSecond: 10
    ttl: 10s
