#  POI deploymet with CSI Driver

apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
  #aadpodidbinding: azure-kv
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - image: "registryvzr4937.azurecr.io/poi:1.0"
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
        imagePullPolicy: Always
        name: poi
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        env:
          - name: WEB_SERVER_BASE_URI
            value: 'http://0.0.0.0'
          - name: WEB_PORT
            value: '80'
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Production'
      volumes:
          - name: secrets
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "secret-provider-kv"
              nodePublishSecretRef:
                name: secrets-store-creds



---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: poi-https
      port: 443
      targetPort: 443
