#  POI deploymet with CSI Driver

apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: "registryvzr4937.azurecr.io/poi:1.0"
        imagePullPolicy: Always
        name: poi
        env:
          - name: WEB_SERVER_BASE_URI
            value: 'http://0.0.0.0'
          - name: WEB_PORT
            value: '80'
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Production'
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        envFrom:
          - secretRef:
              name: mydbsecrets
---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: poi-https
      port: 443
      targetPort: 443
