apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-secrets-keyvault
spec:
  provider: azure
  parameters:
    keyvaultName: "aks-secrets-keyvault"
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectType: secret
        - |
          objectName: SQL-PASSWORD
          objectType: secret
        - |
          objectName: SQL-DBNAME
          objectType: secret
        - |
          objectName: SQL-SERVER
          objectType: secret
    tenantId: "xxxx"   
