# creating the secret provder class and mappings.
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "secret-provider-kv"
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: ka-ohkeyvault0818
    objects:  |
      array:
        - |
          objectName: "DatabaseLogin"
          objectAlias: "SQL_USER"
          objectType: secret
        - |
          objectName: "DatabasePassword"
          objectAlias: "SQL_PASSWORD"
          objectType: secret
        - |
          objectName: "Databaseserver"
          objectAlias: "SQL_SERVER"
          objectType: secret
        - |
          objectName: "Databasename"
          objectAlias: "SQL_DBNAME"
          objectType: secret
    resourceGroup: teamResources
    subscriptionId: b53a5b8e-b158-4114-89f7-4a254169c6d6
    tenantId: 54869ea4-a406-460c-abb3-b3997b0e6b5e 
